---
- hosts: app
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull image from DockerHub
      docker_image:
        name: "amankube/myapp"
        tag: "0d876f5"
        source: pull

    - name: Run Node.js container
      docker_container:
        name: myapp
        image: "amankube/myapp:0d876f5"
        state: started
        ports:
          - "80:3000"
        restart_policy: always

